### ISSUE TITLE
[BUG] AutoBalancerManager seems to be invalid

### ISSUE THREAD

**Issue by funky-eyes** [AutoMQ/automq#1002]
### Version & Environment

通过阅读源码，发现无论是broker的producer进行上报metrics（实则是EmptyMeter），还是controller侧的AutoBalancerManager，他似乎没有在任何消费代码中进行尝试重平衡，在开源的automq中，我只要同时重启3个节点，最终topic的partition只会在一个节点中，无论怎么压测，流量一样时倾斜到一台broker上，无法负载均衡和自动重平衡。

By reading the source code, I found that whether it is the broker's producer for reporting metrics (which is really EmptyMeter) or the controller side of the AutoBalancerManager, it seems that he didn't try to rebalance in any of the consuming code, in the open-source automq, I just need to reboot 3 at the same time. In the open source automq, I just restart 3 nodes at the same time, and eventually the topic's partition will only be in one node, no matter how to pressure test, the traffic will be tilted to one broker at the same time, and there is no way to load-balance and auto-rebalance.

### How to reproduce the issue?

1.
2.
3.

### Additional information

Please attach any relevant logs, backtraces, or metric charts.

**Comment by SCNieh** [comment]
1. AutoMQ detects any anomalies from ClusterModel, which is updated by LoadRetriever when consuming from internal topic __auto_balancer_metrics
2. please make sure you have enabled AutoBalancer (disabled by default) in both broker and controller by using following props:
broker: metric.reporters=kafka.autobalancer.metricsreporter.AutoBalancerMetricsReporter
controller: autobalancer.controller.enable=true
3. if the problem still exists, please provide the steps to reproduce and attach the latest snippet of auto-balancer.log

**Comment by funky-eyes** [comment]
> 1. AutoMQ detects any anomalies from ClusterModel, which is updated by LoadRetriever when consuming from internal topic __auto_balancer_metrics
> 2. please make sure you have enabled AutoBalancer (disabled by default) in both broker and controller by using following props:
>    broker: metric.reporters=kafka.autobalancer.metricsreporter.AutoBalancerMetricsReporter
>    controller: autobalancer.controller.enable=true
> 3. if the problem still exists, please provide the steps to reproduce and attach the latest snippet of auto-balancer.log

This should be my problem, I didn't turn on `autobalancer.controller.enable`，but I found in LoadRetriever#retrieve that only the updateClusterModel was performed, and I didn't find any rebalancing through the ClusterModel.

**Comment by SCNieh** [comment]
> > 1. AutoMQ detects any anomalies from ClusterModel, which is updated by LoadRetriever when consuming from internal topic __auto_balancer_metrics
> > 2. please make sure you have enabled AutoBalancer (disabled by default) in both broker and controller by using following props:
> >    broker: metric.reporters=kafka.autobalancer.metricsreporter.AutoBalancerMetricsReporter
> >    controller: autobalancer.controller.enable=true
> > 3. if the problem still exists, please provide the steps to reproduce and attach the latest snippet of auto-balancer.log
> 
> This should be my problem, I didn't turn on `autobalancer.controller.enable`，but I found in LoadRetriever#retrieve that only the updateClusterModel was performed, and I didn't find any rebalancing through the ClusterModel.

Pls refer to kafka.autobalancer.detector.AnomalyDetector#detect0 for details of detecting anomalies and kafka.autobalancer.executor.ControllerActionExecutorService#execute for executing the reassignment

**Comment by funky-eyes** [comment]
> detect0

thx.
