### ISSUE TITLE
[Enhancement] Switch log appender from DailyRollingFileAppender to RollingFileAppender

### ISSUE THREAD

**Issue by daniel-y** [AutoMQ/automq#1033]
### Who is this for and what problem do they have today?
Currently, Kafka employs the DailyRollingFileAppender for log rotation, but it cannot configure maximum file numbers in log4j, potentially leading to disk space issues.

### Why is solving this problem impactful?
Fortunately, log4j offers a RollingFileAppender that supports configuring the maxBackupIndex, allowing us to limit the maximum disk space used by log files.

### Additional notes
More details please refer to: https://logging.apache.org/log4j/1.x/apidocs/org/apache/log4j/RollingFileAppender.html

**Comment by daniel-y** [comment]
I saw that this issue has been fixed on the main branch via: https://github.com/AutoMQ/automq/pull/1092. How about cherry-picking this commit to the 1.0 branch?

**Comment by warr99** [comment]
> @warr99 I saw that this issue has been fixed on the main branch via: #1092. How about cherry-picking this commit to the 1.0 branch?

Got it! I will do that.
