### ISSUE TITLE
[Good first issue] Object Storage performance baseline

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1082]
## Background
We require performance benchmarks for various cloud object storage systems to determine the optimal number of simultaneous read and write operations for these storages.

## Requirements
Get S3/OSS/COS/BOS/OBS performance baseline:
- #getObject latency for different range size
  - latency: avg, p50, p99, max
  - range size: 16KB、64KB、128KB、512KB、1MB、2MB、4MB、8MB、16MB、32MB
- #putObject latency for different part size
  - latency: avg, p50, p99, max
  - part size: 4MB, 8MB, 16MB, 32MB
- #mutipartUpload latency for different part size
  - uploadPart & complete latency: avg, p50, p99, max
  - part size: 8MB, 16MB, 32MB
- #uploadPartCopy latency for different part size
  - uploadPartCopy & complete latency: avg, p50, p99, max
  - part size: 8MB，16MB， 32MB，64MB，128MB，256MB，512MB，1GB，2GB，4GB

## Ref.
- https://github.com/minio/warp

**Comment by warr99** [comment]
# OSS Performance Test Data

## getObj

- **Test Time:** 100
- **Object Size:** 512M
- **Test Description:** Downloading parts of sizes ranging from 16KB to 512MB from an object of size 512MB, with each part separated by 1M.

### Statistics About `getObj`

| Part Size | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|-----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 16KB      | 14.7     | 11       | 27       | 69       | 3            | 760          | 14.1        |
| 64KB      | 15.2     | 11       | 28       | 69       | 3            | 508          | 13.5        |
| 128KB     | 16.6     | 12       | 29       | 76       | 4            | 924          | 15.5        |
| 512KB     | 23.0     | 18       | 37       | 91       | 7            | 1226         | 19.7        |
| 1MB       | 34.3     | 28       | 53       | 125      | 13           | 1587         | 24.0        |
| 2MB       | 40.4     | 34       | 61       | 122      | 19           | 1265         | 22.2        |
| 4MB       | 55.7     | 48       | 82       | 160      | 28           | 825          | 26.4        |
| 8MB       | 82.1     | 72       | 119      | 209      | 50           | 949          | 35.7        |
| 16MB      | 137.2    | 123      | 189      | 286      | 89           | 1862         | 51.1        |
| 32MB      | 242.6    | 223      | 322      | 472      | 166          | 1291         | 67.1        |

## putObj

- **Test Times:** 100

### Statistics About `putObj`

| Part Size | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|-----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 4MB       | 151.5    | 139      | 188      | 662      | 97           | 662          | 63.6        |
| 8MB       | 263.1    | 243      | 353      | 538      | 182          | 538          | 67.6        |
| 16MB      | 499.4    | 480      | 601      | 1303     | 366          | 1303         | 114.3       |
| 32MB      | 916.3    | 872      | 1134     | 1824     | 643          | 1824         | 191.9       |

## multipartUpload

- **Object Size:** 512MB
- **Test Times:** 100

### Statistics About `multipartUpload`

| Part Size | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|-----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 8MB       | 379.7    | 282      | 765      | 1158     | 156          | 2697         | 233.7       |
| 16MB      | 526.3    | 487      | 693      | 1085     | 327          | 3348         | 151.6       |
| 32MB      | 962.4    | 919      | 1190     | 1669     | 644          | 2738         | 193.2       |

### Statistics About `multipartUploadComplete`

| Part Size | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|-----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 8MB       | 98.4     | 85       | 150      | 280      | 32           | 737          | 52.3        |
| 16MB      | 95.7     | 85       | 141      | 272      | 49           | 272          | 42.1        |
| 32MB      | 87.8     | 78       | 129      | 216      | 45           | 216          | 36.6        |

## uploadPartCopy

- **Object Size:** 1. 512MB, 2. 4096MB, 3. 8192MB
- **Test Time:** 50

### Statistics About `uploadPartCopy`

| Part Size  | Avg (ms)   | 50% (ms)  | 90% (ms)  | 99% (ms)  | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|------------|------------|-----------|-----------|-----------|--------------|--------------|-------------|
| 8MB        | 271.3      | 256       | 350       | 481       | 167          | 950          | 63.9        |
| 16MB       | 480.7      | 460       | 591       | 832       | 327          | 1858         | 102.1       |
| 32MB       | 874.5      | 845       | 1026      | 1467      | 637          | 3021         | 164.8       |
| 64MB       | 1753.8     | 1722      | 2021      | 2535      | 1267         | 3990         | 237.2       |
| 128MB      | 3524.2     | 3469      | 3989      | 4803      | 2658         | 5595         | 377.7       |
| 256MB      | 6798.1     | 6740      | 7451      | 8393      | 5660         | 8723         | 488.1       |
| 512MB      | 13751.9    | 13578     | 14950     | 17017     | 12036        | 17263        | 916.2       |
| 1024MB     | 26475.4    | 26364     | 28252     | 29663     | 23916        | 32881        | 1262.9      |
| 2048MB     | 51900.7    | 51883     | 54678     | 57002     | 46678        | 57821        | 2061.7      |
| 4096MB     | 115760.8   | 116312    | 121782    | 129546    | 106193       | 129546       | 5078.6      |

### Statistics About `uploadPartCopyComplete`

| Part Size | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|-----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 8MB       | 101.4    | 92       | 137      | 151      | 76           | 163          | 21.4        |
| 16MB      | 104.8    | 87       | 132      | 145      | 70           | 150          | 32.1        |
| 32MB      | 89.4     | 81       | 128      | 135      | 63           | 138          | 27.2        |
| 64MB      | 151.6    | 130      | 150      | 268      | 108          | 268          | 58.8        |
| 128MB     | 101.8    | 95       | 119      | 127      | 83           | 130          | 13.7        |
| 256MB     | 106.2    | 106      | 120      | 139      | 81           | 144          | 23.0        |
| 512MB     | 123.8    | 89       | 175      | 254      | 65           | 286          | 81.9        |
| 1024MB    | 120.2    | 118      | 191      | 211      | 65           | 232          | 50.7        |
| 2048MB    | 100.4    | 86       | 124      | 130      | 84           | 134          | 20.3        |
| 4096MB    | 105.2    | 104      | 136      | 136      | 71           | 146          | 25.2        |

# S3 Performance Test Data

## Environment
- **Region**: cn-northwest-1
- **Test Machine Type**: 8V64G

## getObject Performance

Tested with an object size of 512MB, downloading parts of varying sizes (16KB, 64KB, etc.) with each part separated by a 1MB gap.

| PartSize | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 16KB     | 14.7     | 14       | 16       | 24       | 10           | 75           | 2.5         |
| 64KB     | 15.3     | 15       | 17       | 24       | 11           | 98           | 2.4         |
| 128KB    | 16.2     | 16       | 18       | 26       | 12           | 115          | 2.6         |
| 512KB    | 21.1     | 20       | 23       | 32       | 15           | 15333        | 82.9        |
| 1MB      | 26.6     | 26       | 30       | 39       | 21           | 70           | 3.3         |
| 2MB      | 37.9     | 37       | 42       | 51       | 32           | 108          | 3.7         |
| 4MB      | 61.0     | 60       | 66       | 79       | 53           | 127          | 4.6         |
| 8MB      | 107.6    | 107      | 114      | 136      | 96           | 164          | 6.5         |
| 16MB     | 198.5    | 198      | 209      | 232      | 171          | 299          | 10.5        |
| 32MB     | 358.5    | 357      | 368      | 391      | 342          | 424          | 9.3         |

## putObject Performance

| PartSize | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 4MB      | 94.4     | 93       | 119      | 476      | 52           | 476          | 44.2        |
| 8MB      | 132.0    | 132      | 165      | 289      | 80           | 289          | 29.9        |
| 16MB     | 176.7    | 178      | 213      | 234      | 129          | 234          | 24.7        |
| 32MB     | 308.8    | 300      | 350      | 508      | 249          | 508          | 38.7        |

## multipartUpload Performance

For a 512MB object:

| PartSize | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 8MB      | 106.0    | 102      | 130      | 192      | 69           | 5080         | 98.7        |
| 16MB     | 191.6    | 182      | 209      | 362      | 119          | 5126         | 177.3       |
| 32MB     | 283.2    | 278      | 309      | 391      | 221          | 738          | 34.3        |

## multipartUploadComplete Performance

For a 512MB object:

| PartSize | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 8MB      | 97.4     | 94       | 118      | 150      | 66           | 244          | 16.1        |
| 16MB     | 87.5     | 85       | 104      | 116      | 74           | 116          | 9.8         |
| 32MB     | 87.1     | 82       | 106      | 135      | 72           | 135          | 13.3        |

## uploadPartCopy Performance

For objects of sizes 512MB, 4096MB, and 8192MB:

| PartSize | Avg (ms)    | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|----------|-------------|----------|----------|----------|--------------|--------------|-------------|
| 8MB      | 206.8       | 203      | 233      | 302      | 136          | 3101         | 85.0        |
| 16MB     | 327.2       | 317      | 348      | 424      | 231          | 5268         | 218.5       |
| 32MB     | 542.7       | 534      | 578      | 638      | 424          | 5501         | 179.7       |
| 64MB     | 1017.1      | 1001     | 1072     | 1183     | 899          | 6001         | 200.0       |
| 128MB    | 1917.7      | 1906     | 2014     | 2177     | 1491         | 6852         | 199.5       |
| 256MB    | 3407.5      | 3394     | 3581     | 3916     | 2958         | 6494         | 185.7       |
| 512MB    | 6329.6      | 6332     | 6547     | 6921     | 5774         | 7443         | 200.4       |
| 1024MB   | 12146.6     | 12112    | 12419    | 13014    | 11569        | 16579        | 393.0       |
| 2048MB   | 24034.4     | 23848    | 24412    | 30605    | 23160        | 33624        | 1016.3      |
| 4096MB   | 47344.7     | 47009    | 48576    | 59459    | 46037        | 59459        | 1490.4      |

## uploadPartCopyComplete Performance

| PartSize | Avg (ms) | 50% (ms) | 90% (ms) | 99% (ms) | Fastest (ms) | Slowest (ms) | StdDev (ms) |
|----------|----------|----------|----------|----------|--------------|--------------|-------------|
| 8MB      | 91.4     | 90       | 94       | 101      | 85           | 101          | 6.0         |
| 16MB     | 85.8     | 82       | 92       | 100      | 82           | 104          | 7.1         |
| 32MB(questionable)     | 85.2     | 83       | 90       | 97       | 80           | 90           | 6.3         |
| 64MB     | 99.2     | 96       | 121      | 131      | 86           | 141          | 11.7        |
| 128MB    | 95.0     | 88       | 98       | 121      | 82           | 124          | 13.9        |
| 256MB    | 88.6     | 87       | 96       | 109      | 72           | 109          | 11.8        |
| 512MB    | 93.6     | 85       | 112      | 119      | 77           | 126          | 18.0        |
| 1024MB   | 79.0     | 80       | 87       | 87       | 72           | 87           | 5.0         |
| 2048MB   | 84.4     | 80       | 97       | 105      | 75           | 107          | 11.5        |
| 4096MB   | 74.4     | 74       | 78       | 80       | 70           | 83           | 2.3         |
