### ISSUE TITLE
[Enhancement] Fast retry on slow S3 request

### ISSUE THREAD

**Issue by SCNieh** [AutoMQ/automq#1096]
As per the best practice for optimizing S3 performance by [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance-guidelines.html#optimizing-performance-guidelines-retry) and [Aliyun](https://help.aliyun.com/zh/oss/support/recommended-design-patterns?spm=a2c4g.11186623.0.0.79e21ae7rjI2Xx#section-7ew-cwd-u21), a fast retry on slow request is expected to take a different path and respond quickly, which is able to improve the performance of catch-up read.

A possible design is to utilize a S3 client pool in which different client has an expected latency baseline for requests with different size, when the time elapsed since request exceeds the baseline by certain threshold, issue a fast retry instead of waiting for the former one

**Comment by DaniilRoman** [comment]
Hi @SCNieh 👋 
Is this issue still relevant? I've checked the code and it looks like it is. 
I'd be interested to take it over but I'd like to ask few questions regarding the possible solution beforehands.

1. First of all, am I understand correctly that the possible changes will touch `AwsObjectStorage.java` and `AbstractObjectStorage.java`?
2. Second of all, am I understand correctly that the idea is having (let's say) a map of a request size to S3AsyncClient and (as an example) `private S3AsyncClient newS3Client(String endpoint, String region, boolean forcePathStyle,
        List<AwsCredentialsProvider> credentialsProviders, int maxConcurrency)` in `AwsObjectStorage.java` will configure timeout based on the new additional parameter? And at the end the pool initialization will look like:

```java
Map<Long, S3AsyncClient> requestSizeInBytesToReadClient = new HashMap<>();

S3AsyncClient client1 = S3AsyncClient.builder()
    .apiCallAttemptTimeout(Duration.ofSeconds(30))
    .build();
S3AsyncClient client2 = S3AsyncClient.builder()
    .apiCallAttemptTimeout(Duration.ofSeconds(60))
    .build();

requestSizeInBytesToReadClient.put(1000, client1);
requestSizeInBytesToReadClient.put(2000, client2);
  ```
 Did I understand the idea correctly?

3. If I understand the idea from section 2 correctly and judging by this [documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/best-practices.html#bestpractice5)  that says that we can configure these timeouts for a query requests:
```
As an alternative to setting these timeout values on the service client, you can use [RequestOverrideConfiguration#apiCallTimeout()](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/RequestOverrideConfiguration.html#apiCallTimeout()) and [RequestOverrideConfiguration#apiCallAttemptTimeout()](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/RequestOverrideConfiguration.html#apiCallAttemptTimeout()) to configure a single request .
```
does it make sense then to calculate the timeout for particular request size in a query time without modifying the client initialisation stage and without having a clients pool?

<img width="774" alt="Screenshot 2024-07-13 at 23 31 30" src="https://github.com/user-attachments/assets/18961000-9b92-4dcf-9b0b-ef6aa398a8d6">


Looking forward for your answer 🙏

**Comment by DaniilRoman** [comment]
I guess this PR closes this issue
https://github.com/AutoMQ/automq/pull/1574
