### ISSUE TITLE
[Good first issue] Add #asyncClose to LocalLog

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1100]
Introduce an #asyncClose method to both LocalLog and ElasticLocalLog. This approach is preferred over altering the signature of the existing #close method, as it helps prevent future merge conflicts.

**Comment by Shuimo03** [comment]
hi, Can I pick this up?

**Comment by superhx** [comment]
> hi, Can I pick this up?

Of course, you're welcome to submit a PR

**Comment by DaniilRoman** [comment]
Hey there 👋 
Since the ticket hasn't had any updated for the months, I decided to take it over, I hope it's fine 🙏
