### ISSUE TITLE
[Good first issue] argparse4j downgraded to 0.7.0

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1101]
- argparse4j downgraded from 0.9.0 to 0.7.0
- revert the ArgumentParses modification https://github.com/AutoMQ/automq/compare/kafka_3_7_0...main
![image](https://github.com/AutoMQ/automq/assets/5719209/8f2f8a91-e75f-48ae-9bbd-ee8401a2a07f)

Please keep the old code format to avoid merge conflict when merging from kafka/trunk.
Check https://github.com/AutoMQ/automq/compare/kafka_3_7_0...main to downgrade argparse4j

**Comment by Shuimo03** [comment]
hi, Can I pick this up?

**Comment by superhx** [comment]
> hi, Can I pick this up?

Of course, you're welcome to submit a PR

**Comment by Amitbhave** [comment]
Is this still in progress, or can I take this over?

**Comment by superhx** [comment]
> Is this still in progress, or can I take this over?

Yes, you can pick it.

**Comment by Shuimo03** [comment]
Sorry I haven't had time lately, I apologize for the PR!

**Comment by Amitbhave** [comment]
@Shuimo03 , I had picked up this issue now. Is it fine with you?

**Comment by Shuimo03** [comment]
@Amitbhave  yes, i am fine, thank you
