### ISSUE TITLE
[Enhancement] Optimize Partition Reassignment logic to avoid NotLeaderOrFollowerException

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1169]
The current Partition Reassignment process, taking the reassignment of P1 from B1 to B2 as an example:
1. Set PartitionRegistration{isr=[B2], replicas=[B2]};
2. B1, upon realizing it is no longer responsible for the partition, begins to shut down;
3. After B1 has completed its partition shutdown, it notifies the Controller to elect a new leader;
4. The Controller sets PartitionRegistration{leader=B2, isr=[B2], replicas=[B2]};
5. B2, upon receiving the notification, starts to open;
6. Once the partition is fully open, it provides messaging capabilities;
Between steps 4 and 6, which lasts about 1.x seconds, Producers/Consumers will receive NotLeaderOrFollowerException and retry their requests.

Expected process:
1. Set PartitionRegistration{isr=[B2], replicas=[B2]};
2. B1, upon realizing it is no longer responsible for the partition, begins to shut down;
3. B2, upon receiving information through Kraft that the streams associated with the partition are closed, begins to open the partition
4. After B2 has opened the partition, it triggers a leader election with the Controller. The Controller sets PartitionRegistration{leader=B2, isr=[B2], replicas=[B2]}

Between steps 1 to 4, clients periodically update Metadata. After step 4, Producers/Consumers will start sending requests to B2

Compatibility: Added automq.version for the evolution of subsequent AutoMQ features/protocols:

Upgrade process:
1. Upgrade all nodes
2. Run `./bin/kafka-features.sh --bootstrap-server localhost:9095 upgrade --feature automq.version=2` to upgrade to V1 version

New cluster: Automatically uses automq.version = LATEST

**Comment by daniel-y** [comment]
For solution 2, what if the partition is going to move to B3 after step 3 before step 4?

**Comment by superhx** [comment]
> For solution 2, what if the partition is going to move to B3 after step 3 before step 4?

If B2 has already completed opening the relevant Stream:
1. After B2 has finished opening, it will proceed to step 4;
2. B2 closes the Partition and the corresponding Streams;
3. B2 an B3 go through steps 1 to 4 again;

If B2 has not yet opened the Stream, but B3 has preemptively opened the Stream:
1. B2 will fail to open the Partition, throwing a StreamFencedException;
2. B3 continues with steps 3 to 4
