### ISSUE TITLE
[BUG] Missing licence

### ISSUE THREAD

**Issue by szepeviktor** [AutoMQ/automq#1510]
### What went wrong?

People cannot use automq without a licence.

Please see https://github.com/szepeviktor/github-repository-inspection

From the email sent by @vintagewang

**Comment by vintagewang** [comment]
Thank you for bringing this to our attention. We understand the importance of easy access to the license file, and we are committed to enhancing its visibility.

We will prioritize this issue and aim to implement improvements promptly. We appreciate your patience and support as we work to make these adjustments.

Please feel free to reach out if you have any further suggestions or need additional information.

https://github.com/AutoMQ/automq/blob/main/licenses/BSL.md

**Comment by szepeviktor** [comment]
Oh! I am sorry.
All licenses are in that directory.

**Comment by szepeviktor** [comment]
GitHub is not able to find a license.
https://github.com/AutoMQ/automq/community
