### ISSUE TITLE
[BUG] When softLimit is greater than maxSize, it will result in an overflow.

### ISSUE THREAD

**Issue by RapperCL** [AutoMQ/automq#1533]
patch: com.automq.stream.s3.wal.impl.block.BlockImpl#BlockImpl
error:: When softLimit is greater than maxSize, it will result in an overflow.
          
![image](https://github.com/AutoMQ/automq/assets/44110731/9f9641f1-2f86-432e-937b-01f178f69c5e)

**Comment by Chillax-0v0** [comment]
Hello, did you encounter an error during runtime? Are there any error logs?

In fact, `BlockImpl` allows the `softLimit` to be greater than `maxSize`. This means that the size of the Block is only restricted by `maxSize`, without considering the `softLimit`.

**Comment by RapperCL** [comment]
> Hello, did you encounter an error during runtime? Are there any error logs?
> 
> In fact, `BlockImpl` allows the `softLimit` to be greater than `maxSize`. This means that the size of the Block is only restricted by `maxSize`, without considering the `softLimit`.

ye， I made a wrong judgment.
