### ISSUE TITLE
Unstable unit test `testHighTrafficBatchDelete`

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq#1582]
@lifepuzzlefun Hello, I noticed that in PR #1572, you added a unit test called `DeleteObjectsAccumulatorTest#testHighTrafficBatchDelete`. 
When I [triggered this test](https://github.com/AutoMQ/automq/actions/runs/9970595224/job/27549838749#step:5:364) in PR #1581, the result was "Failed," as shown in the image. However, after running it again, the result was "Passed".
![image](https://github.com/user-attachments/assets/54eb48a0-3700-4a34-ad2f-48e30819d0d8)
The changes I made in the PR are not related to this test. It seems that this test is somewhat unstable. Could you help address this issue?

**Comment by lifepuzzlefun** [comment]
sure, i'll fix it in time.
