### ISSUE TITLE
[BUG] Mem leak 

### ISSUE THREAD

**Issue by lifepuzzlefun** [AutoMQ/automq#1731]
### Version & Environment
commit ed986c9c9298b1cb

### What went wrong?

run for 3 days 1:3 write:read, and failover very often.

200MB/s inbound request each node 3 data node in cluster.

(both read from earliest)

the jvm cpu high load and the heap size grows.

### How to reproduce the issue?
have no idea.

### Additional information

Please attach any relevant logs, backtraces, or metric charts.

**Comment by lifepuzzlefun** [comment]
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/ab549515-fb23-4b87-bb65-16fed5b961b5">

this problem each time startup a new cluster will be occur in 3 days.

need some idea to how to find out the leak. I can provide more information as needed.

**Comment by superhx** [comment]
Could you dump the heap?

**Comment by lifepuzzlefun** [comment]
fix by https://github.com/AutoMQ/automq/commit/13657af1b9d44cf3254d9280f5d3f60c8e6b1f03 
because when metadata catch up the epoch 0 ref not release cause all the metadata snapshot not released.
