### ISSUE TITLE
[Enhancement] Support only controller node

### ISSUE THREAD

**Issue by lifepuzzlefun** [AutoMQ/automq#1746]
### Who is this for and what problem do they have today?
1. current config is not work when the kraft only controller start.
2. the controller won't have wal. 
3. the metric reporter may not start on kraft controller. (when deploy the controller quorum start first, there will be no metric report topic at first.
4. maybe more.

### Why is solving this problem impactful?
controller and broker deploy only themself is painful.

**Comment by SCNieh** [comment]
@lifepuzzlefun hi, I just tested with latest commit in main branch and works fine with starting just one node in controller mode
1. can you pls provide more information like the configs you use and what kind of error you observed
2. the controller itself does not need wal to start
3. the metrics reporter for autobalancer only starts in broker node, and the metrics reporter topic will be created once there is at least one broker joined the cluster

**Comment by lifepuzzlefun** [comment]
> @lifepuzzlefun hi, I just tested with latest commit in main branch and works fine with starting just one node in controller mode
> 
> 1. can you pls provide more information like the configs you use and what kind of error you observed
> 2. the controller itself does not need wal to start
> 3. the metrics reporter for autobalancer only starts in broker node, and the metrics reporter topic will be created once there is at least one broker joined the cluster

thanks for reply I'll deploy one new cluster later : - )

**Comment by lifepuzzlefun** [comment]
@SCNieh hi, it seems the new main branch can config only process.role to controller and not not need wal and metric reporter. cool !
