### ISSUE TITLE
Contacting the author

### ISSUE THREAD

**Issue by wlwl2** [AutoMQ/automq#1938]
I got an e-mail from @vintagewang recently and I am unable to send any mail back to that e-mail address. Not sure what to do about that.

**Comment by vinaysshenoy** [comment]
I did too, seems like it's a fake profile? There is nothing to suggest that the github account linked has been involved in this project at all.

**Comment by KaimingWan** [comment]
@wlwl2 Thank you for giving the feedback. I guess there may have some issues with his mailbox. You can connect to his linkedin account for further communication. Btw, if you have any other questions about AutoMQ. You can join our slack community: https://join.slack.com/t/automq/shared_invite/zt-29h17vye9-thf31ebIVL9oXuRdACnOIA .  I am willing to help you.

**Comment by KaimingWan** [comment]
@vinaysshenoy Hi,thanks for giving the feedback.  @vintagewang is not a fake profile.  He may find that you are interested in this kind of project, so he contact you to check whether you have interests.

**Comment by vinaysshenoy** [comment]
@KaimingWan Please don't spam people who are not involved in this project in any capacity.

**Comment by Privat33r-dev** [comment]
I suggest to [report spam](https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam) for anyone else who encountered it.

**Comment by SkyLeite** [comment]
Stop spamming people.

**Comment by 0dminnimda** [comment]
> I suggest to [report spam](https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam) for anyone else who encountered it.

Unconsented email is not a good marketing strategy, so it should have a punishment 👆

**Comment by PrivateGER** [comment]
> Since this issue is not related to the AutoMQ project itself. I closed it. If you guys have more questions about AutoMQ and our team. Join our slack community for help or contact us via email [support@automq.com](mailto:support@automq.com). Thanks you.

Stop spamming people, you absolute cretin.

**Comment by jschnall** [comment]
I received spam also, from xiaorui.w@automq.org. Not something I'll be using.
