### ISSUE TITLE
[BUG] Fetch Stream Out of Bound

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq#1970]
Version: 1.1.2-rc1

What's wrong: 
![image](https://github.com/user-attachments/assets/3578e6df-f6f5-439a-96a1-849c52f8e622)

What happened:
![image](https://github.com/user-attachments/assets/2dd2e9ce-1388-476f-b043-7171938283da)
In the logs, we can see that a segment swap occurred before the issue happened. During this swap, the "log" segment was replaced with the "log.cleaned" segment, the latter of which used the problematic Stream-300979.

https://github.com/AutoMQ/automq/blob/f2066cbe0c8aaa0dfc4ce861b6e064f738b687da/core/src/main/scala/kafka/log/streamaspect/ElasticLogSegmentManager.java#L100-L118
In the code, we can see that before trimming a stream, the minimum offset for each stream is calculated. Specifically, if a stream is not being used by any segment, it will be trimmed to the end.
However, when calculating the minimum offset, the `inflightCleanedSegments` (a member variable) and `meta.getSegmentMetas()` (a method parameter) do not represent the same view at the same point in time. This discrepancy can lead to the incorrect assumption that a stream is not being used by any segment.

**Comment by superhx** [comment]
-
