### ISSUE TITLE
[BUG] Readahead fail

### ISSUE THREAD

**Issue by lifepuzzlefun** [AutoMQ/automq#2131]
### Version & Environment
1.2

### What went wrong?

<img width="1611" alt="image" src="https://github.com/user-attachments/assets/0c0b26d9-dacd-41bc-8533-8ebe5ed537c0">

### How to reproduce the issue?

no idea. no failover not large traffic.

### Additional information

no more information

**Comment by lifepuzzlefun** [comment]
暂时不知道有啥影响，不过目前看的话我们的集群里部分节点一天会出个两三次

**Comment by superhx** [comment]
Please get more log info `grep TRIM_STREAM server.log | grep streamId=4302`. Maybe the readahead try read outdated data. @lifepuzzlefun

**Comment by lifepuzzlefun** [comment]
> Please get more log info `grep TRIM_STREAM server.log | grep streamId=4302`. Maybe the readahead try read outdated data. @lifepuzzlefun

agree, after check the long run log the object not exist for outdated object.
