### ISSUE TITLE
helm or k8s operator to deploy automq for kafka 

### ISSUE THREAD

**Issue by Cloud-Yao** [AutoMQ/automq#652]
### Background

helm or k8s operator to deploy automq for kafka

**Comment by joaocc** [comment]
Was there any new development on this area? Thanks

**Comment by vintagewang** [comment]
> Was there any new development on this area? Thanks

Running AutomQ on Kubernetes requires complex EBS detach and attach operations. Currently, this feature is supported in the Enterprise Edition of AutomQ, and there is no support plan for the Community version at this time. Thank you for your attention. If you need to evaluate the Enterprise Edition of AutomQ, please feel free to contact us.
