### ISSUE TITLE
[BUG] For Adaptive Memory-Related Questions

### ISSUE THREAD

**Issue by funky-eyes** [AutoMQ/automq#965]
### What went wrong?
https://github.com/AutoMQ/automq-for-kafka/compare/1.0.1...1.0.2#diff-5828875a162ccd326ddb05e2dc8d535581ed89b2d8780c4425668913901efc71R45-R46

如果堆外内存没有有效限制,是否将有可能导致oom killer?
我提出一种内存分配策略,以80%的内存作为上限,将35%作为堆内存,45%作为堆外
比如2c4g,并且我认为不应该设置Xms,这将有助于在流量低谷的时候将内存归还回操作系统,并且jdk17+zgc的搭配对于堆内的快速垃圾回收已经不是什么大问题了.
-Xmx1400m -XX:MaxDirectMemorySize=1800m
2c16g为例
-Xmx5600m -XX:MaxDirectMemorySize=7200m
这样是否更为合适呢?

If there is no effective limit on out-of-heap memory, is it possible to cause an oom killer?
I propose a memory allocation strategy with an upper limit of 80% of memory, 35% as heap memory, and 45% as off-heap
For example, 2c4g, and I don't think Xms should be set, which will help to return memory to the operating system when traffic is low, and the combination of jdk17 + zgc is no longer a big problem for fast garbage collection in the heap.
-Xmx1400m -XX: MaxDirectMemorySize=1800m
2C16g as an example
-Xmx5600m -XX: MaxDirectMemorySize=7200m
Is this more appropriate?

### How to reproduce the issue?

1.
2.
3.

### Additional information

Please attach any relevant logs, backtraces, or metric charts.

**Comment by Chillax-0v0** [comment]
1. 目前默认默认会将 75% 的物理内存分配给 JVM 堆，确实没有对堆外内存的大小进行限制。但是，在默认情况下，`s3.stream.allocator.policy` 默认会被配置为 `POOLED_HEAP`，即，s3stream 的各个 cache 均会使用堆内内存。在这种场景下，其他地方（例如 netty, wal）对于堆外内存的使用是较小且可忽略的，所以不限制堆外内存大小也不会触发 OS OOM Killer.
  补充说明：在 v1.0.2 之前，默认会分配 6g 堆内 + 6g 堆外，同时 s3stream 的各个 cache 会使用堆外内存（而非堆内）。但在 v1.0.2 后，我们修改了这个行为（如前所述，均使用堆内，详见#943）。这样做的原因是，有部分用户在使用时会遇到 glibc 中默认内存分配器 ptmalloc2 导致的非预期 OOM 问题，将内存分配器切换到 jemalloc 可以解决这个问题（可以参考[这篇文章](https://developer.aliyun.com/article/894765)）。但是，为了让用户尽可能方便地快速体验 AutoMQ，我们修改了默认的内存分配策略（均使用堆内）。如果希望获得更好的性能，可以在配置 jemalloc 的前提下，手动修改环境变量 `KAFKA_HEAP_OPTS` 与配置 `s3.stream.allocator.policy` 来使用堆外内存。

2. 考虑到 AutoMQ 作为一个独立的服务，一般来说不会和其他应用混部，将其堆大小设置为固定值（ms==mx）是可以接受的，且可以带来更稳定与可预期的性能表现。当然，我们将 JVM 堆设置为固定值也仅为默认行为，用户可以通过修改环境变量 `KAFKA_HEAP_OPTS` 来按照自己的需求进行配置。
